with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/zixyos/goloader/service:
    interfaces:
      Service:
