// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	serviceloader "github.com/zixyos/goloader/service"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *MockService) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockService_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockService_Expecter) Name() *MockService_Name_Call {
	return &MockService_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockService_Name_Call) Run(run func()) *MockService_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Name_Call) Return(_a0 string) *MockService_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Name_Call) RunAndReturn(run func() string) *MockService_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *MockService) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockService_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Run(ctx interface{}) *MockService_Run_Call {
	return &MockService_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockService_Run_Call) Run(run func(ctx context.Context)) *MockService_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Run_Call) Return(_a0 error) *MockService_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Run_Call) RunAndReturn(run func(context.Context) error) *MockService_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetServiceID provides a mock function with given fields: serviceID
func (_m *MockService) SetServiceID(serviceID serviceloader.UUID) {
	_m.Called(serviceID)
}

// MockService_SetServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServiceID'
type MockService_SetServiceID_Call struct {
	*mock.Call
}

// SetServiceID is a helper method to define mock.On call
//   - serviceID serviceloader.UUID
func (_e *MockService_Expecter) SetServiceID(serviceID interface{}) *MockService_SetServiceID_Call {
	return &MockService_SetServiceID_Call{Call: _e.mock.On("SetServiceID", serviceID)}
}

func (_c *MockService_SetServiceID_Call) Run(run func(serviceID serviceloader.UUID)) *MockService_SetServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(serviceloader.UUID))
	})
	return _c
}

func (_c *MockService_SetServiceID_Call) Return() *MockService_SetServiceID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetServiceID_Call) RunAndReturn(run func(serviceloader.UUID)) *MockService_SetServiceID_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *MockService) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Stop(ctx interface{}) *MockService_Stop_Call {
	return &MockService_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockService_Stop_Call) Run(run func(ctx context.Context)) *MockService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Stop_Call) Return(_a0 error) *MockService_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Stop_Call) RunAndReturn(run func(context.Context) error) *MockService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
